GET http://localhost:3000/shoppinglists
// get all lists //
###

POST http://localhost:3000/shoppinglists Content-Type: application/json

{
"title": "list", "createdAt": "2024-02-06", "updatedAt": "2024-01-04T23:03:10.635Z", "items": []
}

###

GET  http://localhost:3000/shoppingList/65c159fd5108c60ab4565e7f
// get specific list //
###

POST htpp://localhost:3000/shoppinglists # Content-Type: application/json
//create a list //


